version: '3'
services:
  projection:
    build: projection/
    volumes:
      - ./projection:/app
      - /app/node_modules
    ports: 
      - "9090:9090"
    command: 'yarn dev'
  poller: 
    build: poller/
    volumes:
      - ./poller:/app
      - /app/node_modules
    command: 'yarn dev'
    depends_on: 
      - 'redis'
  api:
    build: api/
    volumes:
      - ./api:/app
      - /app/node_modules
    command: 'yarn dev'
    depends_on:
      - 'redis'
      - 'influx'

networks:
  default:
    external:
      name: good-human
