version: '3'
services:
  fb:
    build: fb/
    working_dir: /usr/src/app
    env_file: secrets.env
    volumes:
      - ./fb:/usr/src/app
      - /usr/src/app/node_modules
    command: "yarn start"
    depends_on: 
      - 'redis'
      - 'influx'
      - 'chronograf'
  wa:
    build: wa/
    env_file: secrets.env
    volumes:
      - ./wa:/app
      - /app/node_modules
    command: 'yarn start'
    cap_add:
      - SYS_ADMIN
    depends_on: 
      - 'redis'
      - 'influx'
      - 'chronograf'
  redis:
    image: redis
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis:/data
    ports:
      - "6379"
    command: "redis-server /usr/local/etc/redis/redis.conf"
  influx: 
    image: influxdb
    volumes:
      - ./influx/init-db.iql:/docker-entrypoint-initdb.d/init-db.iql
      - ./influx/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - ./influx/data1:/var/lib/influxdb
    ports: 
      - "8086"
  chronograf:
    image: chronograf
    ports:
      - "8888"
    command: ['chronograf', '--influxdb-url=http://influx:8086']
    depends_on:
      - 'influx'

networks:
  default:
    external:
      name: good-human
